stages:
    - fastdl
    - deploy
    - gitguardian
    - github


fastdl:
  stage: fastdl
  script: ./scripts/fastdl.sh
  only:
    - master
  needs: []
  tags:
    - chi

deploy:
  stage: deploy
  script: ./scripts/ci.sh
  only:
    - master
  needs:
    - fastdl
  tags:
    - chi

gitguardian:
  image: gitguardian/ggshield:latest
  stage: gitguardian
  script: ggshield scan ci
  needs: []
  tags:
  - chi-docker
  only:
  - master

github:
  stage: github
  script: ./scripts/gh.sh
  only:
    - master
  needs: [gitguardian]
  tags:
    - chi
