stages:
    - github
    - fastdl
    - deploy

github:
  stage: github
  script: ./scripts/gh.sh
  only:
    - master
  needs: []
  tags:
    - chi

fastdl:
  stage: fastdl
  script: ./scripts/fastdl.sh
  only:
    - master
  needs: []
  tags:
    - chi

deploy:
  stage: deploy
  script: ./scripts/ci.sh
  only:
    - master
  needs: []
  tags:
    - chi
